ktor:
  application:
    dependencies:
      - you.yearof.app.database.DatabaseKt.provideDatabase
      - you.yearof.app.database.repositories.ProvidersKt.accountRepository
      - you.yearof.app.database.repositories.ProvidersKt.captureRepository
      - you.yearof.app.services.TokenServiceKt.provide
      - you.yearof.app.scheduler.LockKt.databaseLock
      - you.yearof.app.scheduler.LockKt.taskExecutor
    modules:
      - you.yearof.app.ApplicationKt.plugins
      - you.yearof.app.routes.accounts.ModuleKt.accountsRoutes
      - you.yearof.app.routes.authentication.ModuleKt.authenticationRoutes
      - you.yearof.app.routes.captures.ModuleKt.capturesRoutes
      - you.yearof.app.scheduler.SchedulerKt.scheduler
  deployment:
    port: ${PORT:8080}
    sslPort: $?SSL_PORT
  security:
    ssl:
      keyStore: $?SSL_KEY_STORE
      keyAlias: $?SSL_KEY_ALIAS
      keyStorePassword: $?SSL_KEY_STORE_PASSWORD
      privateKeyPassword: $?SSL_PRIVATE_KEY_PASSWORD

database:
  url: ${DATABASE_URL:}
  username: ${DATABASE_USERNAME:}
  password: ${DATABASE_PASSWORD:}
  migrate: ${DATABASE_MIGRATE:true}

  pool:
    max-size: ${DATABASE_POOL_MAX_SIZE:10}
    min-idle: ${DATABASE_POOL_MIN_IDLE:0}
    idle-timeout: ${DATABASE_POOL_IDLE_TIMEOUT:PT10M}
    max-lifetime: ${DATABASE_POOL_MAX_LIFETIME:PT30M}
    connection-timeout: ${DATABASE_POOL_CONNECTION_TIMEOUT:PT30S}
    validation-timeout: ${DATABASE_POOL_VALIDATION_TIMEOUT:PT5S}
    validation-query: ${DATABASE_POOL_VALIDATION_QUERY:SELECT 1}

jwt:
  issuer: ${TOKEN_ISSUER:https://yearof.you}
  secret: ${TOKEN_SECRET:}
