ktor:
  application:
    dependencies:
      - you.yearof.app.database.DatabaseKt.provideDatabase
      - you.yearof.app.database.repositories.SqlAccountRepositoryKt.provide
    modules:
      - you.yearof.app.ApplicationKt.module
      - you.yearof.app.routes.authentication.ModuleKt.authenticationRoutes
  deployment:
    port: 8080

database:
  url: ${DATABASE_URL:}
  username: ${DATABASE_USERNAME:}
  password: ${DATABASE_PASSWORD:}
  migrate: ${DATABASE_MIGRATE:true}

  pool:
    max-size: ${DATABASE_POOL_MAX_SIZE:10}
    min-idle: ${DATABASE_POOL_MIN_IDLE:0}
    idle-timeout: ${DATABASE_POOL_IDLE_TIMEOUT:PT10M}
    max-lifetime: ${DATABASE_POOL_MAX_LIFETIME:PT30M}
    connection-timeout: ${DATABASE_POOL_CONNECTION_TIMEOUT:PT30S}
    validation-timeout: ${DATABASE_POOL_VALIDATION_TIMEOUT:PT5S}
    validation-query: ${DATABASE_POOL_VALIDATION_QUERY:SELECT 1}
