package you.yearof.app.database

import androidx.room.AutoMigration
import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.sqlite.SQLiteDriver
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

internal const val DatabaseName = "year-of-you.db"

fun buildDatabase(
    driver: SQLiteDriver = BundledSQLiteDriver(),
    initializer: (String) -> RoomDatabase.Builder<AppDatabase>,
): AppDatabase =
    initializer(DatabaseName)
        .setDriver(driver)
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()

@Database(
    version = 3,
    entities = [Capture::class],
    autoMigrations = [AutoMigration(from = 1, to = 2), AutoMigration(from = 2, to = 3)],
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun captures(): CaptureDao
}

@Suppress("KotlinNoActualForExpect") // Implementation generated by ConstructedBy annotation on AppDatabase
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
