package you.yearof.app.database

import androidx.compose.runtime.Composable
import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO

internal const val DatabaseName = "year-of-you.db"

@Composable
expect fun rememberDatabase(): AppDatabase

internal fun RoomDatabase.Builder<AppDatabase>.commonConfiguration() {
    setDriver(BundledSQLiteDriver())
    setQueryCoroutineContext(Dispatchers.IO)
}

@Database(entities = [Capture::class], version = 1)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun captures(): CaptureDao
}

@Suppress("KotlinNoActualForExpect") // Implementation generated by ConstructedBy annotation on AppDatabase
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
